import localFont from 'next/font/local';
import './globals.css';

export const metadata = {
  title: 'FAQs',
  description: 'Generated by Burak Durmuşoğlu',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        {children}
      </body>
    </html>
  );
}
